sudo: required
dist: trusty
language: go
go:
  - 1.5

env:
  matrix:
    - TEST_SUITE="--static"
    - TEST_SUITE="--unit"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git
script: sh -v ./runtests.sh $TEST_SUITE
after_success:
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=.coverage-go/coverage.out -service=travis-ci
