sudo: required
dist: trusty
language: go
go:
  - 1.5

env:
  matrix:
    - TEST_SUITE="--static"
    - TEST_SUITE="--unit"

script: sh -v ./run-checks $TEST_SUITE
after_success:
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=.coverage-go/coverage.out -service=travis-ci
